name: Student App CI to Jira

on:
  push:
    branches: ["main"]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install 3.9

      - name: Install dependencies
        working-directory: student_app_v3/student_app_v3
        run: uv sync --frozen

      - name: Run Tests
        working-directory: student_app_v3/student_app_v3
        run: uv run pytest --junitxml=report.xml
        continue-on-error: true

      - name: Report Results to Jira (Xray)
        uses: mikepenz/xray-action@v3
        with:
          username: ${{ secrets.XRAY_CLIENT_ID }}
          password: ${{ secrets.XRAY_CLIENT_SECRET }}
          testFormat: 'junit'
          testPaths: 'report.xml'
          projectKey: 'SAV'